<?php
/**
 * Implements hook_field_extra_fields().
 */
function gpol_field_extra_fields() {
  $extra['node']['politico'] = array(
    'display' => array(
      'politico_chart_news_votes' => array(
        'label' => t('Politico chart news votes'),
        'description' => 'Adds Politico chart news votes',
        'weight' => 0,
      ),
    ),
  );
  return $extra;
}

/**
 * Implements hook_node_view().
 */
function gpol_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'politico' && $view_mode == 'full') {
    $node->content['politico_chart_news_votes'] = array(
      '#theme' => 'gpol_politico_chart_news_votes',
    );
  }
}

/**
 * Implements hook_theme().
 */
function gpol_theme($existing, $type, $theme, $path) {
  return array(
    'gpol_politico_chart_news_votes' => array(
      'variables' => array('node' => NULL, 'view_mode' => NULL),
    ),
  );
}


/**
 * Function theme of request perusal link.
 */
function theme_gpol_politico_chart_news_votes($variables) {
  $output = gpol_display_politico_chart_news_votes();
  return $output;
}

function gpol_display_politico_chart_news_votes() {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'noticias')
    ->fieldCondition('field_politicos_afectados','target_id', arg(1), '=');
  $result = $query->execute();
  if (isset($result['node'])) {
    $news_items_nids = array_keys($result['node']);
    $voting_up_counter = 0;
    $voting_down_counter = 0;
    $result = db_select('votingapi_vote', 'v')
      ->fields('v')
      ->condition('entity_id', $news_items_nids,'IN')
      ->execute();
    while($record = $result->fetchAssoc()) {
      if ($record['value'] == 1) {
        $voting_up_counter++;
      }
      else {
        $voting_down_counter++;
      }
    }
    $chart = array(
      '#type' => 'chart',
      '#chart_type' => 'pie',
      '#chart_library' => 'google',
      '#legend_position' => 'right',
      '#data_labels' => TRUE,
      '#tooltips' => FALSE,
    );
    $chart['pie_data'] = array(
      '#type' => 'chart_data',
      '#title' => t('Gender'),
      '#labels' => array('Noticia Positiva', 'Noticia Negativa'),
      '#data' => array($voting_up_counter, $voting_down_counter),
    );

    return '<div class="gpol-graph-voting"><span>.</span>' . drupal_render($chart) . '</div>';
  }
  return '';
}

/**
 * Implements hook_form_alter().
 */
function gpol_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'views_exposed_form' && $form_state['view']->name == 'partidos_politicos') {
    $label = $form['#info']['filter-name']['label'];
    $form['name']['#placeholder'] = t($label);
  }
}
